eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

server:
  port: 9301

spring:
  application:
    name: order

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/product?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        input:
          destination: order_test
        output:
          destination: order_test
        order:
          group: order-group

  redis:
    database: 0
    host: localhost
    port: 6379
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1

feign:
  hystrix:
    enabled: true

#hystrix 熔断机制
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        sleepWindowInMilliseconds: 3000
        requestVolumeThreshold: 5
        errorThresholdPercentage : 30
ribbon:
  #请求处理的超时时间
  ReadTimeout: 3000
  #请求连接的超时时间
  ConnectTimeout: 3000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

