eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

server:
  port: 9301

spring:
  application:
    name: order

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        input:
          destination: order_test
        output:
          destination: order_test
        order:
          group: order-group

  redis:
    database: 0
    host: localhost
    port: 6379